print("Hello world!")
print("Hello again")
print("I only type this to complete ex01 :)")
print("This is fun... kind of")
print('Yay!')
print("I'd much rather you 'not'")
print('I "said" do not touch this')
print("Printing 'ANOTHER' line")
#print("Not printing this one")
print("I did print just one line but I'm not going to commit that")